// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgK9qr9wLWSHQ1gUBtXoH_7VX36lj656M',
    appId: '1:540577531010:web:8b6640e55fbaa85e74209b',
    messagingSenderId: '540577531010',
    projectId: 'typegram-backend',
    authDomain: 'typegram-backend.firebaseapp.com',
    storageBucket: 'typegram-backend.appspot.com',
    measurementId: 'G-5W71NLLF79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDobDqWmkHK_kqiqTMT4Bv0U9HcFNcTpb0',
    appId: '1:540577531010:android:4c67ec7da6fe9caf74209b',
    messagingSenderId: '540577531010',
    projectId: 'typegram-backend',
    storageBucket: 'typegram-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuOmt7TEOh0AZfqDAnc1ASA4Vxky-g3us',
    appId: '1:540577531010:ios:b9e1be383d80f0cb74209b',
    messagingSenderId: '540577531010',
    projectId: 'typegram-backend',
    storageBucket: 'typegram-backend.appspot.com',
    iosBundleId: 'com.example.typegramApp',
  );
}
